### ISSUE TITLE
As a Devops, I would like to leverage observability and monitoring for our hosted client applications

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/howard#122]
Currently, our hosted applications operate without a centralized system for monitoring metrics and managing alerts. This situation limits our ability to proactively address performance issues, optimize resources, and enhance the overall reliability of our services. To address this, we propose integrating OpenTelemetry, Azure Monitor and Grafana, aiming to establish a centralized monitoring framework that enhances visibility into our applications health.

## Design

![image](https://github.com/ai-cfia/howard/assets/73133692/7d15e939-4783-46ea-bd25-34ca1d70d658)

### OpenTelemetry integration

- [x] #193
- [x] #124
- [x] [Deploy an OpenTelemetry operator to manage telemetry received from hosted apps.](https://github.com/ai-cfia/howard/issues/13)
- [x] #125
- [ ] Add OpenTelemetry logging into Nachet-backend.
- [ ] Add OpenTelemetry logging into Finesse-backend.

### OpenTelemetry - Grafana integration

- [ ] Enable metrics and logs for Nachet deployment with a Dashboard in Grafana.
- [ ] Enable metrics and logs for Finesse deployment with a Dashboard in Grafana.
- [ ] Configure AlertManager on Prometheus
- [ ] [add 500 internal server error alerts through emails](https://github.com/ai-cfia/howard/issues/23).
- [ ] Enable alertManager alerts through Teams.

References : 
- [AlertManager](https://github.com/prometheus/alertmanager) 
- [OpenTelemetry Operator](https://github.com/open-telemetry/opentelemetry-operator)
- [OTEL Collector](https://github.com/open-telemetry/opentelemetry-collector)
- [Grafana Tempo](https://github.com/grafana/tempo)
- [Grafana Loki](https://github.com/grafana/loki)
- Hosted Grafana instance : https://grafana.inspection.alpha.canada.ca/
- Why ? [Words](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=python#why-is-microsoft-azure-monitor-investing-in-opentelemetry) from Microsoft about Azure Monitor and Opentelemetry

**Comment by ThomasCardin** [comment]
Note for your diagram: prometheus can't receive traces. Only metrics.

**Comment by SonOfLope** [comment]
> Note for your diagram: prometheus can't receive traces. Only metrics.

I used what is being said in this doc : https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/alertmanagerexporter

Am i misunderstanding ?

**Comment by ThomasCardin** [comment]
No AlertManager seems good. I was talking about the link between otel-collector and prometheus

**Comment by rngadam** [comment]
What is the performance impact of collecting this telemetry across our apps?

**Comment by ThomasCardin** [comment]
majority of this issues is done (monitoring stack), the rest will be done in seperate issues
