### ISSUE TITLE
As a DevSecOps, I would like to migrate all of Howard's documentation from the dev-rel-doc repository into the howard repository, in order to consolidate documentation resources

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#237]
## TODO

- [ ] Migrate howard dev-rel-doc documentation to the howard repo
- [x] Update the README.md
- [x] Update the project description
- [ ] Deploy mkdocs for this repo
