### ISSUE TITLE
Create a kubernetes cluster for Azure

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#3]
Replicate what was done inside this issue #1, but for AWS. After this is done, we should be able to have persistence across the clusters (GCP, AWS, AZURE)

For more information. Check the ADR at https://github.com/ai-cfia/dev-rel-docs/pull/86

Steps to complete : 
- [x]  [Set up Terraform workflow pipeline to initialize, plan, and apply Terraform configurations securely in Azure, managing infrastructure as code with versioned state management.](https://github.com/ai-cfia/infra/issues/28)
- [x] Set up module for creating a kubernetes AKS cluster with terraform for staging environment
- [x] [Setup vault in the cluster with related terraform ressources.](https://github.com/ai-cfia/howard/issues/45)
- [x] Set up [cert-manager](https://github.com/ai-cfia/howard/pull/53)
- [x] #58 
- [x] #27 
....

**Comment by ThomasCardin** [comment]
Check this PR to deploy what is needed https://github.com/ai-cfia/infra/pull/4

**Comment by ThomasCardin** [comment]
The cluster must be created using Terraform
