### ISSUE TITLE
As a devops, I want to deploy a separate PostgreSQL instance for Fertiscan so we can have full control over the database environment

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/howard#393]
## Description

**Context**  
Currently, Fertiscan's database shares the same PostgreSQL deployment as Nachet, which is in a deployment we do not control.

**Problem Statement**  
We need to have a dedicated PostgreSQL instance for Fertiscan deployed in our own resource group. This would give us full control over database performance, scalability, security and costs monitoring while eliminating external dependencies on Nachet's infrastructure.

## TODO

- [ ] Create 2 Database server (Test/Prod)
- [ ] Update the secrets to represent the new architecture (Nachet & FertiScan)
- [ ] Deploy the live schema (Nachet & FertiScan)
- [ ] Implement alerts and docs to manage our Database instances

## Acceptance Criteria

- A dedicated PostgreSQL instance is deployed in our own resource group.
- Fertiscan is fully migrated to the new PostgreSQL instance without data loss.
- All existing connections to the database are updated to point to the new instance.
- All previous tests are passing
- Documentation is created to describe this decision
- Ensure minimal downtime

**Comment by Francois-Werbrouck** [comment]
Secrets have been updated in https://github.com/ai-cfia/ailab-datastore. All tests are passing on the new PostgreSQL instance.

Vault Secrets have been updated in:
- `kv/fertiscan/database` (v.2 added db_url)
- `kv/fertiscan/backend` (v.23 updated fertiscan_db_url)
- `kv/fertiscan-dev/`  (v.4 updated fertiscan_db_url)
- `kv/ailab-datastore` (v3. updated fertiscan_db_url)

We need to bump versions in the necessary repositories for the next deployment

**Comment by k-allagbe** [comment]
Closing this as done.
