### ISSUE TITLE
Automate webtop environment deployment using Jinja2 templating

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#399]
## Executive summary

The goal of this project is to streamline the deployment process for Webtop environments, facilitating rapid setup for new team members and existing team members needing development environments. By utilizing templating and automation, we can ensure consistent, efficient rollouts of these instances.

Users will be able to choose from the following instances for their Webtop deployment ([source](https://docs.linuxserver.io/images/docker-webtop/#application-setup)):

- **latest** ✅ XFCE Alpine
- **ubuntu-xfce** ✅ XFCE Ubuntu
- **fedora-xfce** ✅ XFCE Fedora
- **arch-xfce** ✅ XFCE Arch
- **debian-xfce** ✅ XFCE Debian
- **alpine-kde** ✅ KDE Alpine
- **ubuntu-kde** ✅ KDE Ubuntu
- **fedora-kde** ✅ KDE Fedora
- **arch-kde** ✅ KDE Arch
- **debian-kde** ✅ KDE Debian
- **alpine-mate** ✅ MATE Alpine
- **ubuntu-mate** ✅ MATE Ubuntu
- **fedora-mate** ✅ MATE Fedora
- **arch-mate** ✅ MATE Arch
- **debian-mate** ✅ MATE Debian
- **alpine-i3** ✅ i3 Alpine
- **ubuntu-i3** ✅ i3 Ubuntu
- **fedora-i3** ✅ i3 Fedora
- **arch-i3** ✅ i3 Arch
- **debian-i3** ✅ i3 Debian
- **alpine-openbox** ✅ Openbox Alpine
- **ubuntu-openbox** ✅ Openbox Ubuntu
- **fedora-openbox** ✅ Openbox Fedora
- **arch-openbox** ✅ Openbox Arch
- **debian-openbox** ✅ Openbox Debian
- **alpine-icewm** ✅ IceWM Alpine
- **ubuntu-icewm** ✅ IceWM Ubuntu
- **fedora-icewm** ✅ IceWM Fedora
- **arch-icewm** ✅ IceWM Arch
- **debian-icewm** ✅ IceWM Debian

## TODO
- [ ] Implement a workflow to capture user inputs and trigger template rendering.
- [ ] Create a Jinja2 templates to dynamically insert user-specific data into webtop yaml files configuration.
- [ ] Establish an email system to automatically notify users with their temporary access credentials.
- [ ] Implement secure storage of secrets in Vault via a self-hosted runner. 
    - This means that secrets from the `webtop-secret.yaml` will be pushed into Vault before the `webtop-secret.yaml` file is pushed to the Howard repository
- [ ] Ensure generated files are automatically committed and pushed to the Howard repository.
- [ ] Validate the workflow to ensure inputs are processed correctly and environments are deployed as intended.
- [ ] Documentation (explain how this workflow can be used and add it to integration documentation)

### Exemples
`templates/webtop-deployment.yaml.j2`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}-webtop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ name }}-webtop
  template:
    metadata:
      labels:
        app: {{ name }}-webtop
    spec:
      containers:
      - name: webtop
        image: linuxserver/webtop:ubuntu-kde
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: webtop-secrets
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: webtop-config-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ name }}-webtop-service
spec:
  type: ClusterIP
  selector:
    app: webtop
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ name }}-webtop-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

`generete-template.py`

```python
import sys
from jinja2 import Environment, FileSystemLoader

def render_template(name):
    file_loader = FileSystemLoader('templates')
    env = Environment(loader=file_loader)
    
    template_name = 'webtop-deployment.yaml.j2'
    template = env.get_template(template_name)
    rendered_content = template.render(
        name=name,
    )
    
    output_filename = template_name.replace('.j2', '')
    with open(output_filename, 'w') as f:
        f.write(rendered_content)

if __name__ == '__main__':
    name = sys.argv[1]
    render_template(name)
```

`webtop-deployment.yaml` (template outcome):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thomas-webtop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thomas-webtop
  template:
    metadata:
      labels:
        app: thomas-webtop
    spec:
      containers:
      - name: webtop
        image: linuxserver/webtop:ubuntu-kde
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: webtop-secrets
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: webtop-config-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: thomas-webtop-service
spec:
  type: ClusterIP
  selector:
    app: webtop
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thomas-webtop-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```
