### ISSUE TITLE
As a developer, I would like to be able to test both index for finesse

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#42]
## Executive Summary
As a developer, I would like to have two deployments for the Finesse application:

- The first one using the azure index.
- The second one using the guidance index.

## Context
Currently, we still do not have separate production, development, and staging environments. This causes problems for testing applications (this will be resolved with this issue: https://github.com/features/issues). Therefore, for now, we need to have both the frontend and backend accessible for testing and demonstrations. This will allow us to compare the results between the two. This issue is linked to this one https://github.com/ai-cfia/azure-db/issues/15

## TODO
- [x] Create a new deployment for Finesse, called finesse-guidance.
- [x] Modify both deployments with the correct environment variables.
- [x] Test the behavior of the deployments.
- [x] Confirm that everything is working correctly.

**Comment by rngadam** [comment]
> (this will be resolved with this issue: https://github.com/features/issues).

did you mean to point to another issue?
