### ISSUE TITLE
As a DevOps, I would like to add tags to my Terraform resources to track the cost of my application within Azure.

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#44]
## Executive summary

The goal is to tag Terraform resources to quantify the cost of each one in order to visualize and improve the expenses made on our resources.

## Context

In order to see the cost of deploying and maintaining our applications, we need to tag our Terraform resources to make it easier to visualize the cost in Azure.

## TODO

- [ ] Define relevant tags for our Terraform resources
- [ ] Apply these tags to our Terraform resources
- [ ] Possiblement Create custom dashboards in Azure

**Comment by ThomasCardin** [comment]
OpenCost will be used to track the cost of our applications
