### ISSUE TITLE
As a DevSecOps, I would like to monitor my system and user applications

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/howard#91]
## Executive Summary

Adding dashboards to Grafana is crucial for visualizing the status of our applications and expediting debugging in case of failures.

## Context

Currently, we lack the ability to observe our applications deployed on our cluster. To address this issue, leveraging Grafana dashboards in conjunction with Prometheus will enable us to visualize various key information. These dashboards will also prove invaluable in identifying the root cause of an application failure promptly.

### System Applications

For our system applications, we frequently utilize Helm charts for deployment. In most cases, it is possible to enable functionalities to expose metrics to Prometheus, which can then be displayed in a dashboard. For many system application dashboards, it is possible to find community-created dashboards on [this website](https://grafana.com/grafana/dashboards/)

### Client Applications

For our client applications, it will be necessary to create dashboards and implement the export of metrics, logs, and traces.

## TODO

- System
    - [x] #97
    - [x] #92
    - [x} Setup and configure a dashboard for Cert-manager
    - [x] #94
    - [x] Setup and configure a dashboard CloudnativePG
    - [x] #93

- Client
    - [ ] ~~Create, setup and configure a dashboard for finesse~~ (https://github.com/ai-cfia/howard/issues/240)
    - [ ] ~~Create, setup and configure a dashboard for nachet~~ (https://github.com/ai-cfia/howard/issues/240)

**Comment by ThomasCardin** [comment]
Finesse and nachet dashboard will be done inside this issue: https://github.com/ai-cfia/howard/issues/240
